
name: testing workflow variables 

on:
  workflow_dispatch:

env:
    cloud: google-cloud
  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
        Greeting: Hello
    steps:
      - name: "alexa"
        run: echo "$cloud, $Greeting, $wow, &gig"
        env:
           wow: fubutsu
      - name: "gigs"
        run: echo "$gig, $wow"
        env: 
           gig: gigitty
